### ISSUE TITLE
No new subtabs under "Rendering" tab

### ISSUE THREAD

**Issue by NeuroGal** [fsotoc/FaReT#1]
Hey,
After following your instructions no new subtabs formed under "Rendering". I tried reinstalling, and tried both the recommended 1.2 version and the old version. All produce the same result.
Looking under utilities\logs I see the attached warnings, but pyqt4 is not available using pip, so I'm not sure what to do.

Thanks in advance!
![err](https://user-images.githubusercontent.com/59836021/95857156-de740180-0d63-11eb-88f3-9d9603b4e4d1.PNG)

**Comment by jhays006** [comment]
I just downloaded the 1.2 nightly build, and it doesn't seem like they package the qt4-plugins folder with makehuman anymore.

MakeHuman 1.1.1 version still has it (I copied their direct link below), but we'll have to make a version separately for MakeHuman 1.2, which also seems to use Python 3.7 instead of 2.7.x.
http://download.tuxfamily.org/makehuman/nightly/makehuman-1.1.1-win32.zip

MakeHuman 1.1.1 doesn't come with a formal "installer," so it will not replace the shortcuts or executables that 1.2 sets up.

Jason

**Comment by NeuroGal** [comment]
Thanks! but I also tried the older version and it still didn't work. I don't know why it didn't recognize it

**Comment by jhays006** [comment]
The error message was helpful for the 1.2 version; can you also print the error for the 1.1.1 version?

Thanks,
Jason

**Comment by jhays006** [comment]
In a last stitch effort to quickly solve the problem (because changing it for 1.2 may take a little longer), I made a prepackaged version in which I was able to open the render tabs: [MakeHuman v1.1.1 bundled with FaReT](https://drive.google.com/file/d/1ny5Nvo-pbWzt9m9JS8W5fKZQCmTE34Dg/view?usp=sharing)

**Comment by NeuroGal** [comment]
thanks!
I will check it works in a few days and let you know if I run into problems.

**Comment by NeuroGal** [comment]
After I download the prepackaged version, what should I do to open it? I tried simply pressing the makehuman application in the head directory but I get this error
![image](https://user-images.githubusercontent.com/59836021/96441433-32726080-1212-11eb-9b12-5e5b7a3e8904.png)

**Comment by jhays006** [comment]
Wow, that's definitely not what should have happened!

It is possible that it is a permission-related error. To what location did you extract the MakeHuman directory?

Also, there should be helpful debug/error log files in the following directory:
(I'm assuming this directory based on the first error you posted)
"C:\Users\galvis\Documents\makehuman\v1\"

Can you attach your "makehuman.log", "makehuman-debug.txt", "python_err.txt", and "python_out.txt" files from that directory?

Thank you,
Jason

**Comment by NeuroGal** [comment]
Thanks for your help!
I am getting confused with all of the different versions I have on my computer, so sorry this is going to be messy --
1) I extracted your zip to C:\Users\galvis\Documents\makehuman (adding a directory named "makehuman-1.1.1-win32 FaReT" with all of the files you bundeled). Earlier I tried executing the application directly from there, but now I also copied it to a few more directories to see if that would help, but it didn't. (same error)
This folder has no log\debug\err txt files - but I have a few more folders so maybe one of them will be helpfull?
2) Folders under C:\Users\galvis\Documents\makehuman:
v1 has just python_out.txt but it's empty, and that folder is mostly empty in general.
Other than that I have 2 other folders in that directory: v1py3 and makehuman-master which I think both correspond to version 1.2, but I'm not sure. Maybe I erased the files I downloaded for version 1.1 before. These do have some of the txt files you mentioned, but I'm not sure it's relevant (uploaded them just in case).
3) Lastly, the shortcut to make human actually refers here - C:\Users\galvis\AppData\Local\makehuman-community\makehuman, not to the other location...

I prefer not to uninstall 1.2 because I already used it with another plugin, but I like your plugin and would be happy to try it out too :-)

Sorry for the mess!
Gal
[makehuman.log](https://github.com/fsotoc/FaReT/files/5408691/makehuman.log)
[makehuman-debug.txt](https://github.com/fsotoc/FaReT/files/5408693/makehuman-debug.txt)
[python_err.txt](https://github.com/fsotoc/FaReT/files/5408694/python_err.txt)
[python_out.txt](https://github.com/fsotoc/FaReT/files/5408695/python_out.txt)

**Comment by jhays006** [comment]
No problem!

There's definitely no need to uninstall 1.2, it's just important to note the differences between 1.1.1 and 1.2 to avoid folder confusion.  

- The 1.1.1 version doesn't use the AppData location that 1.2 uses.
- While the 1.1.1 executable is wherever you ultimately extract the prepackaged zip, it generates the Documents/makehuman/v1/ path under your username. 
- The v1 folder does correspond to 1.1.1, and I bet you're right that v1py3 corresponds to 1.2.

The attached log files there are definitely for 1.2.0.

So, if the log files are nonexistent or empty at the v1 folder, it could be crashing really early in its runtime.
For version 1.1.1, there are other people who had the error you are experiencing without FaReT plugins [i.e.](http://www.makehumancommunity.org/forum/viewtopic.php?f=3&t=14865&start=20)
Although 1.2 definitely works on your computer, does MakeHuman 1.1.1 run on your computer _without_ FaReT installed?

Thanks,
Jason

**Comment by NeuroGal** [comment]
Hey,
You are right. MakeHuman 1.1.1 doesn't work! I downloaded the standard MakeHuman release with no extras bundled and it failed in exactly the same way. I thought I tried 1.1.1 before because I downloaded from github (which is written under the old version section), but it's also 1.2.0. Misleading, sorry about that.
Anyway - I checked everything they write in the link you sent, and nothing works. I triple checked permissions are ok, closed windows antivirus, made sure all characters in the path are ok, and nothing works...
So I guess I will have to wait for the version of FaReT with MakeHuman 1.2.
Thanks for all of your help!

**Comment by jhays006** [comment]
> Hey,
> After following your instructions no new subtabs formed under "Rendering". I tried reinstalling, and tried both the recommended 1.2 version and the old version. All produce the same result.
> Looking under utilities\logs I see the attached warnings, but pyqt4 is not available using pip, so I'm not sure what to do.
> 
> Thanks in advance!
> ![err](https://user-images.githubusercontent.com/59836021/95857156-de740180-0d63-11eb-88f3-9d9603b4e4d1.PNG)

There's a new version of FaReT for you to try out now!

Let me know if you have any problems.
Jason

**Comment by NeuroGal** [comment]
Awesome thank you!
